# -*- coding: utf-8 -*-
"""ExaplainableAPI.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CesI23LUw_ZXlSSqIDGpD_jYIgsk8xko

# **Install Libs**
"""

"""# **IMPORTS**"""

# prompt: crie um classe em python chamada ExplainableAPI com o método load_data que recebe o caminho, o separador e retorna um x e um y
import pandas as pd
import numpy as np

import seaborn as sns
import matplotlib.pyplot as plt
import plotly.express as px

from sklearn.preprocessing import MinMaxScaler
import tensorflow as tf
from keras.models import load_model
# from multipledispatch import dispatch
import matplotlib.pyplot as plt

import lime.lime_tabular # !pip install lime==0.1.1.37
import shap #!pip install shap==0.46.0
import os
"""# **GENERAL API**"""

class ExplainableAPI:
  QUERY_FUNGI = '''SELECT
            f.name AS Fungi_Name,
            v.VOC_Category,
            COUNT(*) AS VOC_Count
        FROM
            FUNGI f
        JOIN
            FUNGI_VOC fv ON f.id = fv.FUNGI_ID
        JOIN
            VOCs v ON fv.VOC_ID = v.id_VOC
        GROUP BY
            f.name, v.VOC_Category
        ORDER BY
            f.name, v.VOC_Category,VOC_Count;
        '''
  QUERY_SENSOR = '''SELECT
            f.name AS Sensor_Name,
            v.VOC_Category,
            COUNT(*) AS VOC_Count
        FROM
            SENSOR f
        JOIN
            SENSOR_VOC fv ON f.id = fv.SENSOR_ID
        JOIN
            VOCs v ON fv.VOC_ID = v.id_VOC
        GROUP BY
            f.name, v.VOC_Category
        ORDER BY
            f.name,VOC_Count, v.VOC_Category;
        '''
  def __init__(self, features_name):
    self.features_name = features_name
    self.output_dir = "xai_outputs"
    os.makedirs(self.output_dir, exist_ok=True)
    
  def load_data(self, path, sep):
      data = pd.read_csv(path, delimiter=sep,header=None)
      print()
      y = data.iloc[:, data.shape[1]-1].values
      x = data.iloc[:,0: data.shape[1]-1].copy().values
      return x, y
  def save_dataframe_to_csv(self, df, filename):
        """
        Salva um DataFrame em CSV na pasta de saída definida (padrão: 'xai_outputs').

        Parâmetros:
        - df: pandas.DataFrame
        - filename: str (ex: 'ensemble_summary.csv')
        """
        try:
            if not isinstance(df, pd.DataFrame):
                raise ValueError("O objeto fornecido não é um DataFrame.")
            
            path = os.path.join(self.output_dir, filename)
            df.to_csv(path, index=False)
            print(f"✅ Arquivo salvo com sucesso: {path}")
        except Exception as e:
            print(f"❌ Erro ao salvar DataFrame em CSV: {e}")
              
  def create_df_2(self, list_weights):
      df = pd.DataFrame({
      'Feature': range(len(list_weights)),
      'Weight': list_weights
      })
      return df

  def get_predicted_class(self, sample, model):
      instancia = np.expand_dims(sample, axis=0)
      result = model.predict(instancia)
      return np.argmax(result[0]) + 1, result[0]

  def create_df(self, list_weights, features):
      df = pd.DataFrame({
      'Feature': features,
      'Weight': list_weights
      })
      return df
      #melhorar isso
  def get_samples_from_db(self, X_train, y_train, predictedClass):
      # Filtrar as instâncias pela classe desejadacd
      indices_classe = np.where(y_train == predictedClass)[0]
      X_classe = X_train[indices_classe]

      # Selecionar 3 exemplos aleatórios das instâncias filtradas
      amostras_aleatorias = X_classe[np.random.choice(X_classe.shape[0], 3, replace=False)]
      # Converter cada exemplo selecionado em um DataFrame e armazenar em um array
      dataframes = [pd.DataFrame(amostra.reshape(1, -1)) for amostra in amostras_aleatorias]
      return dataframes

  def plot_cycles(self,newDF):
    # Plotando os dataframes em gráficos separados
    for i, df in enumerate(newDF):
        fig = plt.figure(figsize=[20,10])
        plt.plot(df.T, label=f'Ciclo {i+1}')
        plt.title(f'Gráfico de Linha do Ciclo {i+1}')
        plt.xlabel('Índice')
        plt.ylabel('Valores')
        plt.legend()
        plt.show()

    # Mostrando o gráfico
    plt.show()

  def weight_by_feature(self, features_name, weight_list):
      # Converte a lista de pesos em um array NumPy para facilitar a manipulação
      weight_array = np.array(weight_list)

      # Calcula o número de linhas que o DataFrame terá
      num_rows = len(weight_list) // len(features_name)

      # Redimensiona o array para ter 'num_rows' linhas e 'len(features_name)' colunas
      reshaped_array = weight_array[:num_rows * len(features_name)].reshape(num_rows, len(features_name))

      # Cria o DataFrame a partir do array redimensionado
      df = pd.DataFrame(reshaped_array, columns=features_name)
      return df

  def get_final_result(self, wigths, feature):
      df = self.create_df(wigths, feature)
      self.ploat_heatmap(df)
      self.ploat_bar(df)
      df1 = self.weight_by_feature(self.features_name, df.Weight)
      df1.max().plot(kind='bar')
      df1.mean().plot(kind='bar')
      return df1

  def get_most_important_features(self, dataFrame, top_feature_number):

      df = self.weight_by_feature(self.features_name, dataFrame.Weight)

      newDf = df.mean().reset_index()
      newDf.columns = ['Column', 'Mean']
      newDf = newDf.sort_values(by='Mean', ascending=False)
      top_features = newDf.head(top_feature_number)
      return top_features

  def concat_all_mothods(self, means_lime, means_shap, means_grad):
      from sklearn.preprocessing import StandardScaler
      scaler = StandardScaler()
      # Calculando as médias das colunas
      means_lime['Mean'] = scaler.fit_transform(means_lime[['Mean']])
      means_shap['Mean'] = scaler.fit_transform(means_shap[['Mean']])
      means_grad['Mean'] = scaler.fit_transform(means_grad[['Mean']])

      # Renomeando as colunas para facilitar a concatenação
      # Adicionando uma coluna para identificar o dataframe
      means_lime['DataFrame'] = 'LIME'
      means_shap['DataFrame'] = 'SHAP'
      means_grad['DataFrame'] = 'GRAD'

      # Concatenando os dataframes
      means_all = pd.concat([means_lime, means_shap, means_grad])
      return means_all, means_lime, means_shap, means_grad

  def get_top_features(self,means_lime,means_shap,means_grad,top_index ):
      df_sorted_1 = means_lime.sort_values(by='Mean', ascending=False)
      df_sorted_2 = means_shap.sort_values(by='Mean', ascending=False)
      df_sorted_3 = means_grad.sort_values(by='Mean', ascending=False)

      # Selecionar as três primeiras linhas
      top_3_1 = df_sorted_1.head(top_index)
      top_3_2 = df_sorted_2.head(top_index)
      top_3_3 = df_sorted_3.head(top_index)

      return top_3_1, top_3_2, top_3_3

  def get_features_in_common(self, df1, df2, df3):
      means_all, means_lime, means_shap, means_grad = self.concat_all_mothods(df1, df2, df3)
      top_3_1, top_3_2, top_3_3 = self.get_top_features(means_lime, means_shap, means_grad, 3 )

      df_concat = pd.concat([top_3_1, top_3_2, top_3_3])
      # Contar a frequência de cada valor na coluna 'Coluna'
      coluna_counts = df_concat['Column'].value_counts()
      # Filtrar os valores que aparecem mais de uma vez
      repeated_sensors = coluna_counts[coluna_counts > 1].index
      # Criar um novo DataFrame com as linhas que têm 'Coluna' repetida
      df_final = df_concat[df_concat['Column'].isin(repeated_sensors)]

      return df_final.sort_values(by='Column')
  
  def get_sensor_repeats(self, df_final):
      coluna_counts = df_final['Column'].value_counts()
      df_counts = pd.DataFrame({
          'Sensors': coluna_counts.index,
          'Repeats': coluna_counts.values
      })
      return df_counts.sort_values(by='Sensors').reset_index(drop=True)

  def get_dict_by_query(self, query_sql, conn):
      cursor = conn.cursor()
      cursor.execute(query_sql)
      conn.commit()
      result = cursor.fetchall()
      result_dict = {}
      for data, category, count in result:
          if data not in result_dict:
              result_dict[data] = {}
          result_dict[data][category] = count
      return result_dict, result

  # Função para verificar compatibilidade e retornar os 3 fungos mais compatíveis
  def find_top_compatible_fungi(self, sensor,fungi_dict,sensor_dict ):
      sensor_categories = sensor_dict.get(sensor, {})
      compatibility = []

      for fungus, categories in fungi_dict.items():
          common_categories = set(sensor_categories.keys()).intersection(categories.keys())
          if len(common_categories) >= 1 and len(common_categories) <=3:#talvez tirar essa segunda c
              common_details = {category: (sensor_categories[category], categories[category]) for category in common_categories}
              compatibility.append((fungus, len(common_categories), common_details))

      # Ordenar por número de categorias compatíveis (maior para menor)
      compatibility.sort(key=lambda x: x[1], reverse=True)

      # Ordenar as categorias compatíveis por quantidade de repetições (maior para menor)
      for i in range(len(compatibility)):
          compatibility[i] = (compatibility[i][0], compatibility[i][1], dict(sorted(compatibility[i][2].items(), key=lambda item: item[1][1], reverse=True)))

      # Retornar os 3 fungos mais compatíveis
      return compatibility[:3], sensor_categories

  def plot_samples_db(self, data):
    for i, cycle in enumerate(data):
        a = np.array(cycle)[0]
        new_df = self.group_sensor(self.features_name, a)
        self.plot_chart_line_df(new_df)

  def group_sensor(self, features_name, row_cycle):
        # Converte a lista de pesos em um array NumPy para facilitar a manipulação
        weight_array = np.array(row_cycle)
        # Calcula o número de linhas que o DataFrame terá
        num_rows = len(row_cycle) // len(features_name)
        # Redimensiona o array para ter 'num_rows' linhas e 'len(features_name)' colunas
        reshaped_array = weight_array[:num_rows * len(features_name)].reshape(num_rows, len(features_name))

        # Cria o DataFrame a partir do array redimensionado
        df = pd.DataFrame(reshaped_array, columns=features_name)

        return df
  # Adicionando uma coluna de índice para o eixo X
  def plot_chart_line_df(self, dataFrame):
      dataFrame['Index'] = dataFrame.index
      # Transformando o DataFrame para o formato longo
      df_long = pd.melt(dataFrame, id_vars=['Index'], var_name='Sensor', value_name='Valor')
      # Plotando o gráfico de linha
      plt.figure(figsize=(14, 8))
      sns.lineplot(data=df_long, x='Index', y='Valor', hue='Sensor')
      plt.xlabel('Index')
      plt.ylabel('Value')
      plt.title('Line chart sensors')
      plt.legend(title='Sensors')
      plt.show()

  def ploat_heatmap(self, dataFrame):
      fig = px.density_heatmap(dataFrame, x='Feature', y='Weight', nbinsx=20, nbinsy=20, color_continuous_scale='Viridis')
      # Atualizar o layout para permitir zoom e melhor visualização
      fig.update_layout(
          title='Dynamic Heatmap of Feature Weightss',
          xaxis=dict(title='Feature'),
          yaxis=dict(title='Weight'),
          autosize=True
      )
      # Mostrar o mapa de calor
      fig.show()

  def ploat_bar(self, dataFrame):
      fig = px.bar(dataFrame, x='Feature', y='Weight', color='Weight', color_continuous_scale='Viridis')
      # Atualizar o layout para permitir zoom e melhor visualização
      fig.update_layout(
          title='Feature Weights Bar Chart',
          xaxis=dict(title='Feature'),
          yaxis=dict(title='Weight'),
          autosize=True
      )
      # Mostrar o gráfico de barras
      fig.show()

"""# **LIME METHOD**"""

class LIME_Method:
  def __init__(self, api):
    self.api = api
    pass
  def run_LIME_Method(self, train_data, test_data, model, class_names):
    print("Running LIME...")

    feature_names = np.array(range(train_data.shape[1]))
    explainer = lime.lime_tabular.LimeTabularExplainer(
        training_data=train_data,
        feature_names=feature_names,
        class_names=class_names,
        discretize_continuous=False  # ou True, dependendo da natureza dos seus dados
    )
    num_features = train_data.shape[1]
    instance = test_data
    explanation = explainer.explain_instance(
        instance,
        model.predict,
        num_features= num_features
    )
    # Print the explanation
    feature , weigths = zip(*sorted(explanation.as_list()))
    weigths_array = np.array(weigths)
    return explanation, feature , weigths_array

  def run_mulltiple_LIME_Method(self, train_data, test_data, model, class_names,REPEATS):
      print("Running LIME...")
      df_results = []
      for i in range(REPEATS):
          print(f"Cicle: {i+1} of {REPEATS}...")
          explanation, index, wiegths = self.run_LIME_Method(train_data=train_data, test_data=test_data, model=model, class_names=class_names)
          dataFrame = self.api.create_df(wiegths, index)
          df = self.api.get_most_important_features(dataFrame, 3)
          df_results.append(df)
      return self.summarize_df(df_results)

  def summarize_df(self, df_results):
      #Colocar isso em um método
      df_final = pd.concat(df_results, ignore_index=True)
      # Contar a frequência de cada valor na coluna 'Coluna'
      coluna_counts = df_final['Column'].value_counts()

      # Filtrar os valores que aparecem mais de uma vez
      repeated_sensors = coluna_counts[coluna_counts > 1].index

      # Criar um novo DataFrame com as linhas que têm 'Coluna' repetida
      df_final = df_final[df_final['Column'].isin(repeated_sensors)]

      # Calcular a média das colunas repetidas
      df_final = df_final.groupby('Column').mean().reset_index()

      df_final = df_final.sort_values(by='Column')
      return df_final

  def plot_bar_chart(self, df_final):
      print(f"DF_Final: {df_final.DataFrame} - {df_final}")
      # Configurar o estilo do Seaborn
      sns.set(style="whitegrid")

      # Criar o gráfico de barras
      plt.figure(figsize=(12, 8))
      barplot = sns.barplot(x='Column', y='Mean', hue='Column', data=df_final, palette='viridis')

      # Adicionar títulos e rótulos
      plt.xlabel('Sensors')
      plt.ylabel('Average')
      plt.title(f"DataFrame Sensors Averages to {df_final.DataFrame}")

      # Mostrar o gráfico
      plt.show()

  def plot_class_proba(self, class_name, explanation):
      # Seus valores de probabilidade
      probabilidades = explanation.predict_proba
      # Nomes das classes para o eixo x do gráfico
      plt.figure(figsize=(10, 7))  # Ajuste o tamanho conforme necessário
      # Criar o gráfico de barras
      plt.bar(class_name, probabilidades)

      # Adicionar título e rótulos aos eixos
      plt.title('Probabilidades das Classes')
      plt.xlabel('Classes')
      plt.ylabel('Probabilidade')

      # Mostrar o gráfico
      plt.show()


"""# **SHAP METHOD**"""

class SHAP_Method:
  def __init__(self, features_name, api):
    self.api = api
    self.features_name = features_name
  def run_SHAP_Method(self, train_data, test_data,model, class_names, npermutations):
    # explainer = shap.KernelExplainer(model.predict, train_data)
    print("Running SHAP...")
    print(f"BEFORE: Type {type(test_data)} and Shap: {test_data.shape}")
    test_data = test_data.reshape(1, -1)
    print(f"AFTER: Type {type(test_data)} and Shap: {test_data.shape}")

    explainer = shap.PermutationExplainer(model.predict, train_data)
    shap_values = explainer.shap_values(test_data, npermutations=npermutations)

    predicted_classes, main_class_predicted = self.get_model_results(model, test_data)

    feature_weights = shap_values[:,:,main_class_predicted][0]  # Sum weights across classes #max_index

    return explainer,shap_values, feature_weights
  
  def run_mulltiple_SHAP_Method(self, train_data, test_data, model, class_names, npermutations, REPEATS):
      print("Running SHAP...")
      df_results = []
      for i in range(REPEATS):
          print(f"Cicle: {i+1} of {REPEATS}...")
          explanation, index, wieghts = self.run_SHAP_Method(train_data=train_data, test_data=test_data, model=model, class_names=class_names, npermutations=npermutations)
          dataFrame = self.api.create_df_2(wieghts)
          df = self.api.get_most_important_features(dataFrame, 3)
          df_results.append(df)
      return self.summarize_df(df_results)

  def get_model_results(self, model, test_data):
      predicted_classes = model.predict(test_data)
      main_class_predicted = np.argmax(predicted_classes)
      return predicted_classes, main_class_predicted

  def summarize_df(self, df_results):
      #Colocar isso em um método
      df_final = pd.concat(df_results, ignore_index=True)
      # Contar a frequência de cada valor na coluna 'Coluna'
      coluna_counts = df_final['Column'].value_counts()

      # Filtrar os valores que aparecem mais de uma vez
      repeated_sensors = coluna_counts[coluna_counts > 1].index

      # Criar um novo DataFrame com as linhas que têm 'Coluna' repetida
      df_final = df_final[df_final['Column'].isin(repeated_sensors)]

      df_final = df_final.sort_values(by='Column')
      return df_final

  def plot_bar_chart(self, df_final):
      # Configurar o estilo do Seaborn
      sns.set(style="whitegrid")

      # Criar o gráfico de barras
      plt.figure(figsize=(12, 8))
      barplot = sns.barplot(x='Column', y='Mean', hue='Column', data=df_final, palette='viridis')

      # Adicionar títulos e rótulos
      plt.xlabel('Sensors')
      plt.ylabel('Average')
      plt.title(f"DataFrame Sensors Averages to {df_final.DataFrame[0]}")

      # Mostrar o gráfico
      plt.show()

"""# **GRAD-CAM**"""

class GRAD_CAM_Method:
  def __init__(self, features_name, api):
    self.api = api
    self.features_name = features_name

  def run_GRAD_CAM_Method(self, test_data, model, class_names, last_layer_name):
      # Selecionar uma instância para visualização
      print("Running GRAD_CAM...")
      instancia = test_data  # Por exemplo, a primeira instância do conjunto de dados

      # Preparar a instância para o modelo (adicionar uma dimensão extra se necessário)
      instancia = np.expand_dims(instancia, axis=0)

      # Obter a saída do modelo para a instância selecionada
      predicao = model.predict(instancia)

      # Obter a classe prevista
      classe_prevista = np.argmax(predicao[0])

      # Obter o output do último layer convolucional
      ultimo_conv_layer = model.get_layer(last_layer_name) #em alguns casos, isso pode mudar

      # Criar um modelo para Grad-CAMVai 
      grad_model = tf.keras.models.Model(
          [model.inputs],
          [ultimo_conv_layer.output, model.output]
      )

      # Obter os gradientes da classe prevista em relação ao último layer convolucional
      with tf.GradientTape() as tape:
          conv_outputs, predictions = grad_model(instancia)
          predictions = tf.convert_to_tensor(predictions)  # Converter para tensor

          # Verificar o tamanho de predictions
          num_classes = predictions.shape[-1]
          if classe_prevista >= num_classes:
              raise ValueError(f"Classe prevista ({classe_prevista}) está fora dos limites (0 a {num_classes-1}).")

          # Garantir que predictions é um tensor de float32
          predictions = tf.cast(predictions, tf.float32)
          print(f"predictions {predictions}")
          print(predictions[0][classe_prevista])
          loss = predictions[0][classe_prevista] #predictions[:, classe_prevista]

      # Gradientes em relação à saída do último layer convolucional
      grads = tape.gradient(loss, conv_outputs)[0]

      # Média ponderada dos canais da saída do layer convolucional
      pooled_grads = tf.reduce_mean(grads, axis=(0, 1))

      # Multiplicar cada canal na saída do feature map pelo "importance" desse canal
      heatmap = tf.reduce_sum(tf.multiply(pooled_grads, conv_outputs[0]), axis=-1)
      return heatmap, grad_model, classe_prevista

  def summarize_df(self, df_results):
      # Concatenar os DataFrames
      df_final = pd.concat(df_results, ignore_index=True)

      # Contar a frequência de cada valor na coluna 'Coluna'
      coluna_counts = df_final['Column'].value_counts()

      # Filtrar os valores que aparecem mais de uma vez
      repeated_sensors = coluna_counts[coluna_counts > 1].index

      # Criar um novo DataFrame com as linhas que têm 'Coluna' repetida
      df_final = df_final[df_final['Column'].isin(repeated_sensors)]

      # Calcular a média das colunas repetidas
      df_final = df_final.groupby('Column').mean().reset_index()

      # Ordenar o DataFrame final pela coluna 'Coluna'
      df_final = df_final.sort_values(by='Column')

      return df_final

  def run_mulltiple_GRAD_Method(self, test_data, model, class_names,last_layer_name, REPEATS):
      print("Running GRAD_CAM...")
      df_results = []
      for i in range(REPEATS):
          print(f"Cicle: {i+1} of {REPEATS}...")
          heatmap, grad_model, classe_prevista = self.run_GRAD_CAM_Method(test_data=test_data, model=model, class_names=class_names,last_layer_name=last_layer_name)
          dataFrame = self.api.create_df_2(heatmap)
          df = self.api.get_most_important_features(dataFrame, 3)
          df_results.append(df)
      return self.summarize_df(df_results)

  def plot_heatmap(self, df_grad):
      # Criar o gráfico de barras
      fig = px.bar(df_grad, x='Feature', y='Weight', color='Weight', color_continuous_scale='Viridis')

      # Atualizar o layout para permitir zoom e melhor visualização
      fig.update_layout(
          title='Gráfico de Barras dos Pesos das Características (Grad-CAM)',
          xaxis=dict(title='Feature'),
          yaxis=dict(title='Weight'),
          autosize=True
      )

      # Mostrar o gráfico de barras
      fig.show()

  def plot_bar_chart(self, df_final):
      # Configurar o estilo do Seaborn
      sns.set(style="whitegrid")

      # Criar o gráfico de barras
      plt.figure(figsize=(12, 8))
      barplot = sns.barplot(x='Column', y='Mean', hue='Column', data=df_final, palette='viridis')

      # Adicionar títulos e rótulos
      plt.xlabel('Sensors')
      plt.ylabel('Average')
      plt.title(f"DataFrame Sensors Averages to {df_final.DataFrame[0]}")

      # Mostrar o gráfico
      plt.show()

"""# **Run all methods**"""
import numpy as np
from scipy.stats import kendalltau

class Metrics:
    @staticmethod
    def calculate_jaccard_index(set1, set2):
        """Índice de Jaccard entre dois conjuntos."""
        if not set1 or not set2:
            return 0.0
        intersection = len(set1.intersection(set2))
        union = len(set1.union(set2))
        return intersection / union

    @staticmethod
    def calculate_overlap_coefficient(set1, set2):
        """Coeficiente de sobreposição entre dois conjuntos."""
        if not set1 or not set2:
            return 0.0
        intersection = len(set1.intersection(set2))
        min_size = min(len(set1), len(set2))
        return intersection / min_size

    @staticmethod
    def calculate_ranking_correlation(df1, df2, method='kendall'):
        """
        Correlação entre rankings de dois DataFrames com colunas: 'Column' e 'Mean'.
        Retorna correlação de Kendall por padrão.
        """
        try:
            # 1. Interseção de colunas comuns
            common_features = sorted(set(df1['Column']).intersection(set(df2['Column'])))
            if not common_features:
                return 0.0

            # 2. Filtragem e alinhamento
            df1_filtered = df1[df1['Column'].isin(common_features)].drop_duplicates(subset='Column').set_index('Column')
            df2_filtered = df2[df2['Column'].isin(common_features)].drop_duplicates(subset='Column').set_index('Column')

            df1_filtered = df1_filtered.loc[common_features]
            df2_filtered = df2_filtered.loc[common_features]

            # 3. Extração dos valores
            scores1 = df1_filtered['Mean'].values
            scores2 = df2_filtered['Mean'].values

            if scores1.shape != scores2.shape:
                raise ValueError(f"Shapes incompatíveis: scores1 {scores1.shape}, scores2 {scores2.shape}")

            # 4. Correlação
            if method == 'kendall':
                tau, _ = kendalltau(scores1, scores2)
                return tau if not np.isnan(tau) else 0.0
            else:
                raise ValueError(f"Método de correlação não suportado: {method}")
        except Exception as e:
            print(f"Erro ao calcular correlação de ranking: {e}")
            return 0.0

class Run_methods:
  def __init__(self, api):
      self.api = api
      self.metrics = Metrics()
      self.LIME = LIME_Method(self.api)
      self.SHAP = SHAP_Method(self.api.features_name, self.api)
      self.GRAD = GRAD_CAM_Method(self.api.features_name, self.api)

  def run_all_methods_mult(self, X_train, X_test, model, class_names, npermutations, last_layer_name, REPEATS):

      df_LIME = self.LIME.run_mulltiple_LIME_Method(train_data=X_train, test_data=X_test, model=model, class_names=class_names, REPEATS=REPEATS)
      df_shap = self.SHAP.run_mulltiple_SHAP_Method(train_data=X_train, test_data=X_test,  model=model, class_names=class_names, npermutations=npermutations, REPEATS=REPEATS)
      df_GRAD = self.GRAD.run_mulltiple_GRAD_Method(test_data=X_test, model=model,class_names=class_names, last_layer_name=last_layer_name, REPEATS=REPEATS)

      df_final = self.api.get_features_in_common(df_LIME, df_shap, df_GRAD)
      df_caounts = self.api.get_sensor_repeats(df_final)

      return df_LIME, df_shap, df_GRAD, df_final, df_caounts

  def run_2_old_methods_mult(self, X_train, X_test, model, class_names,last_layer_name, REPEATS):

      df_LIME = self.LIME.run_mulltiple_LIME_Method(train_data=X_train, test_data=X_test, model=model, class_names=class_names, REPEATS=REPEATS)
      df_shap = pd.DataFrame(data={'Column':[0],'Mean':[0],'DataFrame':'SHAP'})
      df_GRAD = self.GRAD.run_mulltiple_GRAD_Method(test_data=X_test, model=model,class_names=class_names, last_layer_name=last_layer_name, REPEATS=REPEATS)

      df_final = self.api.get_features_in_common(df_LIME, df_shap, df_GRAD)
      df_caounts = self.api.get_sensor_repeats(df_final)

      return df_LIME, df_shap, df_GRAD, df_final, df_caounts
  
  def run_2_methods_mult(self, X_train, X_test, model, class_names, last_layer_name, REPEATS, method_names):

    df_LIME = self.LIME.run_mulltiple_LIME_Method(train_data=X_train, test_data=X_test, model=model, class_names=class_names, REPEATS=REPEATS) if "LIME" in method_names else pd.DataFrame(data={'Column':[0],'Mean':[0],'DataFrame':'LIME'})
    df_shap = self.SHAP.run_mulltiple_SHAP_Method(train_data=X_train, test_data=X_test,  model=model, class_names=class_names, npermutations=50, REPEATS=REPEATS) if "SHAP" in method_names else pd.DataFrame(data={'Column':[0],'Mean':[0],'DataFrame':'SHAP'})
    df_GRAD = self.GRAD.run_mulltiple_GRAD_Method(test_data=X_test, model=model, class_names=class_names, last_layer_name=last_layer_name, REPEATS=REPEATS) if "GRAD" in method_names else pd.DataFrame(data={'Column':[0],'Mean':[0],'DataFrame':'GRAD'})

    df_final = self.api.get_features_in_common(df_LIME, df_shap, df_GRAD)
    df_caounts = self.api.get_sensor_repeats(df_final)

    return df_LIME, df_shap, df_GRAD, df_final, df_caounts

  def run_all_methods_once(self, X_train, X_test, model, class_names, npermutations,last_layer_name):

      explanation, index, wiegths = self.LIME.run_LIME_Method(train_data=X_train, test_data=X_test, model=model, class_names=class_names)
      dataFrame_1 = self.api.create_df(wiegths, index)
      df_LIME = self.api.get_most_important_features(dataFrame_1, 3)

      explainer,shap_values, feature_weights = self.SHAP.run_SHAP_Method(train_data=X_train, test_data=X_test, model=model, class_names=class_names, npermutations=npermutations)
      dataFrame_2 = self.api.create_df_2(list_weights=feature_weights)
      df_shap = self.api.get_most_important_features(dataFrame_2, 3)
     
      heatmap, grad_model, classe_prevista = self.GRAD.run_GRAD_CAM_Method(test_data=X_test, model=model,class_names=class_names, last_layer_name=last_layer_name)
      dataFrame_3 = self.api.create_df_2(heatmap)
      df_GRAD = self.api.get_most_important_features(dataFrame_3, 3)

      df_final = self.api.get_features_in_common(df_LIME, df_shap, df_GRAD)
      df_caounts = self.api.get_sensor_repeats(df_final)

      return df_LIME, df_shap, df_GRAD, df_final, df_caounts

  def run_2_methods_once(self, X_train, X_test, model, class_names, last_layer_name):

      explanation, index, wiegths = self.LIME.run_LIME_Method(train_data=X_train, test_data=X_test, model=model, class_names=class_names)
      dataFrame_1 = self.api.create_df(wiegths, index)
      df_LIME = self.api.get_most_important_features(dataFrame_1, 3)

      df_shap = pd.DataFrame(data={'Column':[0],'Mean':[0],'DataFrame':'SHAP'})

      heatmap, grad_model, classe_prevista = self.GRAD.run_GRAD_CAM_Method(test_data=X_test, model=model,class_names=class_names, last_layer_name=last_layer_name)
      dataFrame_3 = self.api.create_df_2(heatmap)
      df_GRAD = self.api.get_most_important_features(dataFrame_3, 3)

      df_final = self.api.get_features_in_common(df_LIME, df_shap, df_GRAD)
      df_caounts = self.api.get_sensor_repeats(df_final)

      return df_LIME, df_shap, df_GRAD, df_final, df_caounts

  def plot_all_bar_charts(self,df_LIME, df_shap, df_GRAD):
      self.LIME.plot_bar_chart(df_LIME)
      if(df_shap.Mean.mean() !=0):
        self.SHAP.plot_bar_chart(df_shap)

      self.GRAD.plot_bar_chart(df_GRAD)

  def get_result_summary(self, df_caounts, db_name, query_fungi, query_sensor):
      import sqlite3
      conn = sqlite3.connect(db_name)
      fungi_dict, fungi = self.api.get_dict_by_query(query_fungi,conn)
      sensor_dict, sensor = self.api.get_dict_by_query(query_sensor,conn)
      result = ""
      top_fungis = []
      top_sensors = {}
      for sensor in df_caounts.Sensors:
          print(f"Sensor: {sensor}")
          top_fungi, top_sensor = self.api.find_top_compatible_fungi(sensor,fungi_dict,sensor_dict)
          top_sensors[sensor] = top_sensor
          top_fungis.append(top_fungi)
          result += f"Os 3 fungos mais compatíveis com o sensor {sensor} são:"
          for fungus, count, details in top_fungi:
              result += f"{fungus} com {count} categorias compatíveis:"
              for category, (sensor_count, fungus_count) in details.items():
                  result += f"  - {category}: Sensor ({sensor_count} vezes), Fungo ({fungus_count} vezes)"
              result += "\n"
      return result, top_fungis, top_sensors
  
  def plot_bar_chart_all_methods(self, dataFrame):
      sns.set(style="whitegrid")
      # Criando a figura com maior DPI e tamanho
      plt.figure(figsize=(12, 8), dpi=200)

      # Criando o gráfico de barras
      sns.barplot(x='Column', y='Mean', hue='DataFrame', data=dataFrame, palette='viridis')

      # Adicionando labels e título
      plt.xlabel('Sensors', fontweight='bold')
      plt.ylabel('Average values', fontweight='bold')
      plt.title('DataFrame Sensors Averages')

      # Rotacionando os nomes das colunas no eixo X
      plt.xticks(rotation=45)

      # Exibindo o gráfico
      plt.show()
    
  def perform_direct_comparison(self, X_train, X_test_instance, model, class_names, npermutations, last_layer_name):
        print("\n" + "="*50)
        print("=== INITIATING DIRECT COMPARISON ===")
        print("="*50 + "\n")

        df_LIME, df_shap, df_GRAD, df_ensemble_final, df_ensemble_counts = \
            self.run_all_methods_once(X_train, X_test_instance, model, class_names, npermutations, last_layer_name)

        print(f"\n--- df_LIME \n{df_LIME} ---")
        print(f"\n--- df_shap \n{df_shap} ---")
        print(f"\n--- df_GRAD \n{df_GRAD} ---")
        print("\n--- Visualizing Individual and Ensemble Results ---")
        # self.plot_all_bar_charts(df_LIME, df_shap, df_GRAD)

        if not df_ensemble_final.empty:                 
            result, top_fungi, sensors_and_categories =  main.get_result_summary(
                df_ensemble_counts,
                base_dir + "/src/MappingVOC_DB.db",
                api.QUERY_FUNGI,
                api.QUERY_SENSOR
            )
            print(f"top_fungi {top_fungi}")
            print(f"top_sensors {sensors_and_categories}")
            # self.plot_bar_chart_all_methods(df_ensemble_final)
        else:
            print("Ensemble plot skipped (DataFrame is empty).")

        # Métricas de Concordância
        metrics = self.metrics
        top_k = 3

        # Extrair features
        top_lime_features = set(df_LIME['Column']) if not df_LIME.empty else set()
        top_shap_features = set(df_shap['Column']) if not df_shap.empty else set()
        top_grad_features = set(df_GRAD['Column']) if not df_GRAD.empty else set()
        top_ensemble_features = set(df_ensemble_final['Column']) if not df_ensemble_final.empty else set()

        # Salvar resultados principais
        self.api.save_dataframe_to_csv(df_LIME, "direct_comparison_LIME.csv")
        self.api.save_dataframe_to_csv(df_shap, "direct_comparison_SHAP.csv")
        self.api.save_dataframe_to_csv(df_GRAD, "direct_comparison_GRAD.csv")
        self.api.save_dataframe_to_csv(df_ensemble_final, "direct_comparison_ENSEMBLE.csv")
        self.api.save_dataframe_to_csv(df_ensemble_counts, "direct_comparison_ENSEMBLE_counts.csv")

        # Calcular métricas
        comparison_metrics = {
            'Comparison': [],
            'Jaccard': [],
            'Overlap': [],
            "Kendall's Tau": []
        }

        def add_metrics(name, df_other, other_features):
            jaccard = metrics.calculate_jaccard_index(top_ensemble_features, other_features)
            overlap = metrics.calculate_overlap_coefficient(top_ensemble_features, other_features)
            kendall = metrics.calculate_ranking_correlation(df_ensemble_final, df_other, method='kendall')

            comparison_metrics['Comparison'].append(f'Ensemble vs {name}')
            comparison_metrics['Jaccard'].append(jaccard)
            comparison_metrics['Overlap'].append(overlap)
            comparison_metrics["Kendall's Tau"].append(kendall)

            print(f"Jaccard (Ensemble vs {name}): {jaccard:.3f}")
            print(f"Overlap (Ensemble vs {name}): {overlap:.3f}")
            print(f"Kendall's Tau (Ensemble vs {name}): {kendall:.3f}")

        print(f"\n--- Concordance Metrics (Top-{top_k} Features) ---")
        if df_LIME is not None and not df_LIME.empty:
            add_metrics("LIME", df_LIME, top_lime_features)
        if df_shap is not None and not df_shap.empty:
            add_metrics("SHAP", df_shap, top_shap_features)
        if df_GRAD is not None and not df_GRAD.empty:
            add_metrics("Grad-CAM", df_GRAD, top_grad_features)

        # Criar e salvar DataFrame de métricas
        df_metrics = pd.DataFrame(comparison_metrics)
        self.api.save_dataframe_to_csv(df_metrics, "direct_comparison_METRICS.csv")

        print("\n--- Summary of Common Features (Ensemble) ---")
        print(df_ensemble_final)
        print("\n--- Sensor Repeats in Ensemble ---")
        print(df_ensemble_counts)

        print("\n" + "="*50)
        print("=== DIRECT COMPARISON COMPLETED ===")
        print("="*50 + "\n")

  def perform_ablation_study(self, X_train, X_test_instance, model, class_names, npermutations, last_layer_name, REPEATS=5):
        print("\n" + "="*50)
        print("=== INITIATING ABLATION STUDY ===")
        print("="*50 + "\n")
        
        metrics = self.metrics

        # 1. Ensemble Completo
        print("\n--- Running Full Ensemble (LIME + SHAP + Grad-CAM) ---")
        df_LIME_full, df_SHAP_full, df_GRAD_full, df_full_ensemble, _ = \
            self.run_all_methods_mult(X_train, X_test_instance, model, class_names, npermutations, last_layer_name, REPEATS)
        df_full_ensemble_copy = df_full_ensemble.copy() # Criar cópia para evitar SettingWithCopyWarning
        df_full_ensemble_copy['Ensemble_Type'] = 'Full'
        print("Full Ensemble Top Features:\n", df_full_ensemble_copy)
        if not df_full_ensemble_copy.empty:
            print("Plot skipped")
            # self.plot_bar_chart_all_methods(df_full_ensemble_copy)
        else:
            print("Full Ensemble plot skipped (DataFrame is empty).")
        self.api.save_dataframe_to_csv(df_full_ensemble_copy, "ablation_full_ensemble.csv")


        # 2. Ablação: LIME + SHAP (removendo Grad-CAM)
        print("\n--- Running Ablation: LIME + SHAP ---")
        _, _, _, df_lime_shap_ensemble, _ = \
            self.run_2_methods_mult(X_train, X_test_instance, model, class_names, last_layer_name, REPEATS, method_names=['LIME', 'SHAP'])
        df_lime_shap_ensemble_copy = df_lime_shap_ensemble.copy()
        df_lime_shap_ensemble_copy['Ensemble_Type'] = 'LIME+SHAP'
        print("LIME+SHAP Ensemble Top Features:\n", df_lime_shap_ensemble_copy)
        if not df_lime_shap_ensemble_copy.empty:
            print("Plot skipped")
            # self.plot_bar_chart_all_methods(df_lime_shap_ensemble_copy)
        else:
            print("LIME+SHAP Ensemble plot skipped (DataFrame is empty).")
        self.api.save_dataframe_to_csv(df_lime_shap_ensemble_copy, "ablation_lime_shap_ensemble.csv")


        # 3. Ablação: LIME + Grad-CAM (removendo SHAP)
        print("\n--- Running Ablation: LIME + Grad-CAM ---")
        _, _, _, df_lime_grad_ensemble, _ = \
            self.run_2_methods_mult(X_train, X_test_instance, model, class_names, last_layer_name, REPEATS, method_names=['LIME', 'GRAD'])
        df_lime_grad_ensemble_copy = df_lime_grad_ensemble.copy()
        df_lime_grad_ensemble_copy['Ensemble_Type'] = 'LIME+GRAD'
        print("LIME+GRAD-CAM Ensemble Top Features:\n", df_lime_grad_ensemble_copy)
        if not df_lime_grad_ensemble_copy.empty:
            print("Plot skipped")
            # self.plot_bar_chart_all_methods(df_lime_grad_ensemble_copy)
        else:
            print("LIME+GRAD-CAM Ensemble plot skipped (DataFrame is empty).")
        self.api.save_dataframe_to_csv(df_lime_grad_ensemble_copy, "ablation_lime_grad_ensemble.csv")


        # 4. Ablação: SHAP + Grad-CAM (removendo LIME)
        print("\n--- Running Ablation: SHAP + Grad-CAM ---")
        _, _, _, df_shap_grad_ensemble, _ = \
            self.run_2_methods_mult(X_train, X_test_instance, model, class_names, last_layer_name, REPEATS, method_names=['SHAP', 'GRAD'])
        df_shap_grad_ensemble_copy = df_shap_grad_ensemble.copy()
        df_shap_grad_ensemble_copy['Ensemble_Type'] = 'SHAP+GRAD'
        print("SHAP+GRAD-CAM Ensemble Top Features:\n", df_shap_grad_ensemble_copy)
        if not df_shap_grad_ensemble_copy.empty:
            print("Plot skipped")
            # self.plot_bar_chart_all_methods(df_shap_grad_ensemble_copy)
        else:
            print("SHAP+GRAD-CAM Ensemble plot skipped (DataFrame is empty).")
        self.api.save_dataframe_to_csv(df_shap_grad_ensemble_copy, "ablation_shap_grad_ensemble.csv")


        # Comparação de Concordância
        top_k = 3
        print("\n--- Concordance Metrics for Ablation Study (vs Full Ensemble) ---")
        full_ensemble_features = set(df_full_ensemble_copy['Column']) if not df_full_ensemble_copy.empty else set()

        if not df_lime_shap_ensemble_copy.empty:
            lime_shap_features = set(df_lime_shap_ensemble_copy['Column'])
            print(f"Jaccard (Full vs LIME+SHAP): {metrics.calculate_jaccard_index(full_ensemble_features, lime_shap_features):.3f}")
            print(f"Kendall's Tau (Full vs LIME+SHAP): {metrics.calculate_ranking_correlation(df_full_ensemble_copy, df_lime_shap_ensemble_copy, method='kendall'):.3f}")
        else:
            print("LIME+SHAP results empty, skipping metrics.")

        if not df_lime_grad_ensemble_copy.empty:
            lime_grad_features = set(df_lime_grad_ensemble_copy['Column'])
            print(f"Jaccard (Full vs LIME+GRAD): {metrics.calculate_jaccard_index(full_ensemble_features, lime_grad_features):.3f}")
            print(f"Kendall's Tau (Full vs LIME+GRAD): {metrics.calculate_ranking_correlation(df_full_ensemble_copy, df_lime_grad_ensemble_copy, method='kendall'):.3f}")
        else:
            print("LIME+GRAD results empty, skipping metrics.")

        if not df_shap_grad_ensemble_copy.empty:
            shap_grad_features = set(df_shap_grad_ensemble_copy['Column'])
            print(f"Jaccard (Full vs SHAP+GRAD): {metrics.calculate_jaccard_index(full_ensemble_features, shap_grad_features):.3f}")
            print(f"Kendall's Tau (Full vs SHAP+GRAD): {metrics.calculate_ranking_correlation(df_full_ensemble_copy, df_shap_grad_ensemble_copy, method='kendall'):.3f}")
        else:
            print("SHAP+GRAD results empty, skipping metrics.")
        
        print("\n" + "="*50)
        print("=== ABLATION STUDY COMPLETED ===")
        print("="*50 + "\n")


  def perform_sensitivity_analysis(self, X_train, X_test_original_instance, model, class_names, npermutations, last_layer_name, num_perturbations=5, noise_strength=0.01):
        print("\n" + "="*50)
        print("=== INITIATING SENSITIVITY ANALYSIS ===")
        print("="*50 + "\n")
        
        metrics = self.metrics
        
        # 1. Explicação da instância original
        print("\n--- Explaining Original Instance ---")
        _, _, _, df_ensemble_orig, _ = \
            self.run_all_methods_once(X_train, X_test_original_instance, model, class_names, npermutations, last_layer_name)
        
        # Verificar se df_ensemble_orig está vazio
        if df_ensemble_orig.empty:
            print("Original ensemble explanation is empty. Skipping sensitivity analysis.")
            return

        original_ensemble_features = set(df_ensemble_orig['Column'])
        
        # Salvar a explicação original para referência
        self.api.save_dataframe_to_csv(df_ensemble_orig, "sensitivity_original_ensemble.csv")

        jaccard_scores = []
        overlap_scores = []
        kendall_scores = []

        for i in range(num_perturbations):
            print(f"\n--- Perturbation {i+1}/{num_perturbations} ---")
            # Adicionar ruído gaussiano à instância
            perturbed_instance = X_test_original_instance + np.random.normal(0, noise_strength, X_test_original_instance.shape)
            
            # Garanta que os valores perturbados ainda estejam dentro de um intervalo razoável (se aplicável)
            # Ex: perturbed_instance = np.clip(perturbed_instance, 0, 1) se os dados forem normalizados entre 0 e 1
            # Se seus dados são de sensor, valores negativos podem ser problemáticos.
            perturbed_instance = np.maximum(0, perturbed_instance) # Garante que não há valores negativos

            _, _, _, df_ensemble_pert, _ = \
                self.run_all_methods_once(X_train, perturbed_instance, model, class_names, npermutations, last_layer_name)
            
            if df_ensemble_pert.empty:
                print(f"Perturbation {i+1}: Ensemble result is empty, skipping metrics for this perturbation.")
                continue

            perturbed_ensemble_features = set(df_ensemble_pert['Column'])
            
            # Salvar cada explicação perturbada
            self.api.save_dataframe_to_csv(df_ensemble_pert, f"sensitivity_perturbed_ensemble_{i+1}.csv")

            # Jaccard Index
            jaccard = metrics.calculate_jaccard_index(original_ensemble_features, perturbed_ensemble_features)
            jaccard_scores.append(jaccard)

            # Overlap Coefficient
            overlap = metrics.calculate_overlap_coefficient(original_ensemble_features, perturbed_ensemble_features)
            overlap_scores.append(overlap)

            # Kendall's Tau (ranking correlation)
            kendall = metrics.calculate_ranking_correlation(df_ensemble_orig, df_ensemble_pert, method='kendall')
            kendall_scores.append(kendall)
            
            print(f"Perturbation {i+1}: Jaccard={jaccard:.3f}, Overlap={overlap:.3f}, Kendall's Tau={kendall:.3f}")

        # Salvar métricas agregadas de sensibilidade
        if jaccard_scores: # Verifica se a lista não está vazia antes de calcular a média
            sensitivity_summary_data = {
                'Metric': ['Average Jaccard Index', 'Average Overlap Coefficient', 'Average Kendall\'s Tau'],
                'Value': [np.mean(jaccard_scores), np.mean(overlap_scores), np.mean(kendall_scores)]
            }
            df_sensitivity_summary = pd.DataFrame(sensitivity_summary_data)
            self.api.save_dataframe_to_csv(df_sensitivity_summary, "sensitivity_metrics_summary.csv")

            print(f"\nAverage Jaccard Index: {np.mean(jaccard_scores):.3f}")
            print(f"Average Overlap Coefficient: {np.mean(overlap_scores):.3f}")
            print(f"Average Kendall's Tau: {np.mean(kendall_scores):.3f}")
        else:
            print("\nNo valid perturbed explanations generated for calculating average metrics.")


        print("\n" + "="*50)
        print("=== SENSITIVITY ANALYSIS COMPLETED ===")
        print("="*50 + "\n")


"""# **Teste e Avaliação**"""

# Exemplo de uso e avaliação
if __name__ == '__main__':
    
    # --- Configurações Iniciais ---
    #Comentar essas duas linhas quando for usar o código para amostras de cultura
    # features_name = [ "MQ-7", "MQ-138", "MQ-3", "MQ-135"]
    # class_names = [ "Glabrata", "Parapsilosis", "glabra_parapsi", "Cryptococcus", "Negative", "Albicans" ]
    
    # Create an instance of the class
    # Albicans = 1
    # Glabrata = 2
    # Haemulonii = 3
    # Kodamaea_ohmeri = 4
    # Krusei = 5
    # Parapsilosis = 6
    #Comentar essas duas linhas quando for usar o código para amostras de sangue
    features_name = ["TGS-826","TGS-2611","TGS-2603","TGS-813","TGS-822","TGS-2602","TGS-823"]
    class_names = ['Albicans', 'Glabrata', 'Haemulonii', 'Kodamaea_ohmeri', 'Krusei', 'Parapsilosis']
    api = ExplainableAPI(features_name)
    import os
    base_dir = os.path.abspath(os.path.dirname(__file__)) if '__file__' in globals() else os.getcwd()
    #Pode ser necessário ajustar o nome e a extensão do modelo dependendo do que você está usando
    # model_path = "best_model.hdf5"  # Substitua pelo caminho do seu modelo
    # model_path = os.path.join(base_dir, "src", "best_model.keras")
    model_path = os.path.join(base_dir, "src", "best_model.hdf5")
    print("Caminho completo do modelo:", model_path)
    print("Existe o arquivo?", os.path.isfile(model_path))

    # --- Carregar Dados ---
    try:
        # Substitua estes caminhos pelos seus arquivos reais!
        X_train, y_train = api.load_data(path=base_dir+"/src/AllCandidas_TRAIN.csv", sep=",")  # Replace with actual path and separator
        X_test, y_test = api.load_data(path=base_dir+"/src/AllCandidas_TEST.csv", sep=",")  # Replace with actual path and separator
        SAMPLE_INDEX = 8# amostra que será selecionada do df de teste: Amostras diferetentes:(0:2),(2:3),(3:4),(4:6),(8:1),(21:5) (indice:classe) Amostras iguais: 9, 12, 17, 19,25,27,40,45,47,49
        
        # X_train, y_train = api.load_data(path="AllCandidas_TRAIN.csv", sep=",")
        # X_test, y_test = api.load_data(path="AllCandidas_TEST.csv", sep=",")
    except FileNotFoundError:
        print("\n" + "="*50)
        print("ATENÇÃO: Arquivos de dados não encontrados!")
        print("Criando dados dummy para demonstração. Por favor, forneça seus arquivos reais para uma avaliação significativa.")
        print("="*50 + "\n")
        # Criar dados dummy para permitir a execução do código de avaliação
        num_features = len(features_name)
        num_train_samples = 100
        num_test_samples = 10
        num_classes = len(class_names)
        X_train = np.random.rand(num_train_samples, num_features)
        y_train = np.random.randint(0, num_classes, num_train_samples)
        X_test = np.random.rand(num_test_samples, num_features)
        y_test = np.random.randint(0, num_classes, num_test_samples)

    # SAMPLE_INDEX = 0 # Amostra que será selecionada do df de teste para explicação
    # Assegura que SAMPLE_INDEX não exceda o tamanho de X_test
    print(f"SAMPLE_INDEX  {SAMPLE_INDEX}")
    if SAMPLE_INDEX >= len(X_test):
        SAMPLE_INDEX = 0 if len(X_test) > 0 else -1
        print(f"SAMPLE_INDEX ajustado para {SAMPLE_INDEX} devido ao tamanho de X_test.")
    
    if SAMPLE_INDEX == -1:
        print("\n" + "="*50)
        print("ERRO: Não há amostras de teste disponíveis para rodar a avaliação. Encerrando.")
        print("="*50 + "\n")
    else:
        X_test_instance = X_test[SAMPLE_INDEX]
        
        # --- Carregar Modelo ---
        try:
            # Substitua este caminho pelo seu arquivo de modelo real!
            # model = tf.keras.models.load_model(model_path)
            model = load_model(model_path, compile=False)  # compile=False para evitar recompilação se não for necessário
            print("Modelo carregado com sucesso.")
        except Exception as e:
            print("\n" + "="*50)
            print(f"ATENÇÃO: Erro ao carregar o modelo: {e}")
            print("Criando um modelo dummy para demonstração. Por favor, forneça seu modelo real para uma avaliação significativa.")
            print("="*50 + "\n")
            # Criar um modelo dummy simples para demonstração
            model = tf.keras.Sequential([
                tf.keras.layers.Input(shape=(len(features_name),)), # Usar Input layer explícito
                tf.keras.layers.Dense(10, activation='relu'),
                tf.keras.layers.Dense(len(class_names), activation='softmax', name='last_dense_layer') # Adiciona um nome ao último layer para Grad-CAM
            ])
            model.compile(optimizer='adam', loss='sparse_categorical_crossentropy', metrics=['accuracy'])
            # Treinar o modelo dummy rapidamente para que 'predict' funcione minimamente
            print("Treinando modelo dummy (1 época)...")
            model.fit(X_train, y_train, epochs=1, verbose=0)
            print("Modelo dummy criado e treinado.")

        # --- Identificar o nome do último layer convolucional para Grad-CAM ---
        last_layer_name = None
        for layer in reversed(model.layers):
            # Prioriza camadas convolucionais (Conv1D, Conv2D, Conv3D)
            if isinstance(layer, (tf.keras.layers.Conv1D, tf.keras.layers.Conv2D, tf.keras.layers.Conv3D)):
                last_layer_name = layer.name
                break
        if last_layer_name is None:
            # Se não houver convolucional, tenta o último layer denso
            if model.layers:
                last_layer_name = model.layers[-1].name
            else:
                last_layer_name = "output_layer_fallback" # Nome genérico se o modelo for muito simples
            print(f"Nenhum layer convolucional encontrado. Usando o último layer '{last_layer_name}' para Grad-CAM (pode não ser ideal).")
        else:
            print(f"Último layer convolucional para Grad-CAM identificado: '{last_layer_name}'")
        
        # --- Instanciar a classe principal de execução ---
        main = Run_methods(api)
        
        # --- EXECUTE AS AVALIAÇÕES ---
        print("\n" + "#"*60)
        print("### INITIATING COMPREHENSIVE XAI ENSEMBLE EVALUATION ###")
        print("#"*60 + "\n")

        # 1. **Comparação Direta** (para uma única instância de teste)
        # Permite ver como o ensemble se compara a cada método individualmente.
        main.perform_direct_comparison(
            X_train=X_train,
            X_test_instance=X_test_instance,
            model=model,
            class_names=class_names,
            npermutations=50, # Número de permutações para SHAP
            last_layer_name=last_layer_name
        )

       # 2. **Estudo de Ablação** (para múltiplas execuções na mesma instância, para agregar resultados)
        #Ajuda a entender a contribuição de cada método para o ensemble.
        #Ajuste REPEATS conforme necessário para significância estatística (e.g., 5, 10, 20).
        main.perform_ablation_study(
            X_train=X_train,
            X_test_instance=X_test_instance,
            model=model,
            class_names=class_names,
            npermutations=50, # Número de permutações para SHAP
            last_layer_name=last_layer_name,
            REPEATS=5 # Número de repetições para a média
        )

        #3. **Análise de Sensibilidade** (perturbando a instância original)
        #Avalia a robustez das explicações do ensemble a pequenas mudanças na entrada.
        #Ajuste `num_perturbations` e `noise_strength` para testar diferentes cenários.
        main.perform_sensitivity_analysis(
            X_train=X_train,
            X_test_original_instance=X_test_instance,
            model=model,
            class_names=class_names,
            npermutations=50, # Número de permutações para SHAP
            last_layer_name=last_layer_name,
            num_perturbations=3, # Quantas vezes perturbar a instância e re-explicar
            noise_strength=0.05 # Força do ruído adicionado (e.g., 5% do desvio padrão esperado)
        )

        print("\n" + "#"*60)
        print("### XAI ENSEMBLE EVALUATION COMPLETED ###")
        print("#"*60 + "\n")

        # --- Exemplo de uso da API de banco de dados (se houver um DB real) ---
        # Substitua 'your_database.db' pelo caminho do seu arquivo de banco de dados SQLite.
        # Remova o comentário das linhas abaixo se você tiver um DB configurado e quiser usar.
        # Por exemplo, se df_final foi o resultado da última chamada de perform_ablation_study:
        # if 'df_final' in locals() and not df_final.empty:
        #     db_name = 'your_database.db' # Nome do seu arquivo de banco de dados
        #     result_summary, top_fungis, top_sensors = main.get_result_summary(
        #         df_final, db_name, api.QUERY_FUNGI, api.QUERY_SENSOR
        #     )
        #     print("\n--- Compatibility Summary from DB ---")
        #     print(result_summary)
        # else:
        #     print("\nSkipping DB compatibility summary: no valid df_final found from evaluation runs.")